spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: -1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      host: localhost
      port: 27011
      username: sample
      password: sample
      database: admin
